# -*- coding: utf-8 -*-
"""Face Detection Using HaarCascade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-NashIPjaJSNjCZsWU2GcgVGxjoIwxpX
"""

pip install opencv-contrib-python

pip install caer

import cv2 
from google.colab.patches import cv2_imshow

img = cv2.imread('./mypic.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2_imshow(gray)

haar_cascade = cv2.CascadeClassifier('./haarcascade_face_detection.xml')

faces_detect = haar_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=3)

print("Number of faces found in the image were {}".format(len(faces_detect)))
for x, y, w, h in faces_detect: 
  cv2.rectangle(img, (x,y), (x+w, y+h), (0, 255, 0), thickness=2)

cv2_imshow(img)

img2 = cv2.imread('./friends.png')
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray2)
faces_detect_new = haar_cascade.detectMultiScale(gray2, scaleFactor=1.1, minNeighbors=6)
print("Number of faces detected in the image is {}".format(len(faces_detect_new)))
for (x, y, w, h) in faces_detect_new: 
  cv2.rectangle(img2, (x,y), (x+w, y+h), (0, 0, 255), thickness=4)
cv2_imshow(img2)